apiVersion: apps/v1
kind: Deployment
metadata:
  name: yenohtessema
  labels:
    app: mywebapp
    tier: frontend
  annotations:
    submitted-by: yenoh-tessema-ugr5405

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mywebapp
      tier: frontend
  template:
    metadata:
      labels:
        app: mywebapp
        tier: frontend
    spec:
      containers:
        - name: mycontainer
          image: devopsjourney1/mywebapp
          ports:
            - containerPort: 80
